export const TRANSACTIONDATA = [
  {
    "TransactionID": "1",
    "DateTime": "2023-10-27T08:30:00",
    "Amount": 100.00,
    "Description": "Grocery shopping",
    "AccountFrom": "Savings Account",
    "AccountTo": "Grocery Store",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "GRO123",
    "Currency": "USD",
    "PaymentMethod": "Credit Card",
    "TransactionCategory": "Food",
    "TransactionTags": ["Groceries", "Food"],
    "UserID": "9876",
    "MerchantID": "6789",
    "Location": "123 Main St"
  },
  {
    "TransactionID": "2",
    "DateTime": "2023-10-26T15:45:00",
    "Amount": 500.00,
    "Description": "Salary deposit",
    "AccountFrom": "Employer",
    "AccountTo": "Savings Account",
    "TransactionType": "Deposit",
    "Status": "Completed",
    "ReferenceNumber": "SAL001",
    "Currency": "USD",
    "PaymentMethod": "Bank Transfer",
    "TransactionCategory": "Income",
    "TransactionTags": ["Salary", "Income"],
    "UserID": "9876",
    "MerchantID": null,
    "Location": null
  },
  {
    "TransactionID": "3",
    "DateTime": "2023-10-25T12:00:00",
    "Amount": 50.00,
    "Description": "Lunch with friends",
    "AccountFrom": "Savings Account",
    "AccountTo": "Restaurant",
    "TransactionType": "Dining",
    "Status": "Completed",
    "ReferenceNumber": "LUNCH123",
    "Currency": "USD",
    "PaymentMethod": "Debit Card",
    "TransactionCategory": "Dining",
    "TransactionTags": ["Restaurant", "Food"],
    "UserID": "1234",
    "MerchantID": "9876",
    "Location": "456 Oak St"
  },
  {
    "TransactionID": "4",
    "DateTime": "2023-10-24T09:15:00",
    "Amount": 200.00,
    "Description": "ATM withdrawal",
    "AccountFrom": "Checking Account",
    "AccountTo": null,
    "TransactionType": "Withdrawal",
    "Status": "Completed",
    "ReferenceNumber": "ATM001",
    "Currency": "USD",
    "PaymentMethod": "ATM Card",
    "TransactionCategory": "Cash Withdrawal",
    "TransactionTags": ["ATM", "Cash"],
    "UserID": "5678",
    "MerchantID": null,
    "Location": "789 Elm St"
  },
  {
    "TransactionID": "5",
    "DateTime": "2023-10-23T14:20:00",
    "Amount": 75.00,
    "Description": "Online shopping",
    "AccountFrom": "Savings Account",
    "AccountTo": "Online Retailer",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "SHOP001",
    "Currency": "USD",
    "PaymentMethod": "PayPal",
    "TransactionCategory": "Shopping",
    "TransactionTags": ["Online Shopping", "Retail"],
    "UserID": "3456",
    "MerchantID": "5432",
    "Location": null
  },
  {
    "TransactionID": "6",
    "DateTime": "2023-10-22T19:30:00",
    "Amount": 30.00,
    "Description": "Movie tickets",
    "AccountFrom": "Savings Account",
    "AccountTo": "Cinema",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "MOVIE123",
    "Currency": "USD",
    "PaymentMethod": "Debit Card",
    "TransactionCategory": "Entertainment",
    "TransactionTags": ["Movies", "Entertainment"],
    "UserID": "6789",
    "MerchantID": "7890",
    "Location": "101 Elm St"
  },
  {
    "TransactionID": "7",
    "DateTime": "2023-10-21T14:00:00",
    "Amount": 300.00,
    "Description": "Monthly rent",
    "AccountFrom": "Checking Account",
    "AccountTo": "Landlord",
    "TransactionType": "Payment",
    "Status": "Completed",
    "ReferenceNumber": "RENT2023",
    "Currency": "USD",
    "PaymentMethod": "Bank Transfer",
    "TransactionCategory": "Housing",
    "TransactionTags": ["Rent", "Housing"],
    "UserID": "1234",
    "MerchantID": null,
    "Location": "456 Oak St"
  },
  {
    "TransactionID": "8",
    "DateTime": "2023-10-20T10:15:00",
    "Amount": 40.00,
    "Description": "Gasoline purchase",
    "AccountFrom": "Checking Account",
    "AccountTo": "Gas Station",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "GAS456",
    "Currency": "USD",
    "PaymentMethod": "Credit Card",
    "TransactionCategory": "Transportation",
    "TransactionTags": ["Gas", "Transportation"],
    "UserID": "5678",
    "MerchantID": "3456",
    "Location": "789 Main St"
  },
  {
    "TransactionID": "9",
    "DateTime": "2023-10-19T17:30:00",
    "Amount": 15.00,
    "Description": "Coffee with friends",
    "AccountFrom": "Savings Account",
    "AccountTo": "Cafe",
    "TransactionType": "Dining",
    "Status": "Completed",
    "ReferenceNumber": "COFFEE001",
    "Currency": "USD",
    "PaymentMethod": "Cash",
    "TransactionCategory": "Dining",
    "TransactionTags": ["Cafe", "Food"],
    "UserID": "2345",
    "MerchantID": "1234",
    "Location": "789 Oak St"
  },
  {
    "TransactionID": "10",
    "DateTime": "2023-10-18T11:45:00",
    "Amount": 85.00,
    "Description": "Electronics purchase",
    "AccountFrom": "Savings Account",
    "AccountTo": "Electronics Store",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "ELEC002",
    "Currency": "USD",
    "PaymentMethod": "Debit Card",
    "TransactionCategory": "Shopping",
    "TransactionTags": ["Electronics", "Shopping"],
    "UserID": "7890",
    "MerchantID": "8765",
    "Location": "101 Main St"
  },
  {
    "TransactionID": "11",
    "DateTime": "2023-10-17T14:30:00",
    "Amount": 120.00,
    "Description": "Utilities payment",
    "AccountFrom": "Checking Account",
    "AccountTo": "Utility Company",
    "TransactionType": "Payment",
    "Status": "Completed",
    "ReferenceNumber": "UTIL001",
    "Currency": "USD",
    "PaymentMethod": "Bank Transfer",
    "TransactionCategory": "Utilities",
    "TransactionTags": ["Bills", "Utilities"],
    "UserID": "3456",
    "MerchantID": null,
    "Location": null
  },
  {
    "TransactionID": "12",
    "DateTime": "2023-10-16T16:00:00",
    "Amount": 65.00,
    "Description": "Concert tickets",
    "AccountFrom": "Savings Account",
    "AccountTo": "Ticket Vendor",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "CONCERT123",
    "Currency": "USD",
    "PaymentMethod": "Credit Card",
    "TransactionCategory": "Entertainment",
    "TransactionTags": ["Concert", "Entertainment"],
    "UserID": "5678",
    "MerchantID": "4321",
    "Location": "456 Main St"
  },
  {
    "TransactionID": "13",
    "DateTime": "2023-10-15T09:00:00",
    "Amount": 25.00,
    "Description": "Bus fare",
    "AccountFrom": "Savings Account",
    "AccountTo": "Public Transportation",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "BUS456",
    "Currency": "USD",
    "PaymentMethod": "Mobile Payment",
    "TransactionCategory": "Transportation",
    "TransactionTags": ["Bus", "Transportation"],
    "UserID": "2345",
    "MerchantID": "1234",
    "Location": null
  },
  {
    "TransactionID": "14",
    "DateTime": "2023-10-14T18:45:00",
    "Amount": 150.00,
    "Description": "Clothing purchase",
    "AccountFrom": "Savings Account",
    "AccountTo": "Clothing Store",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "CLOTH001",
    "Currency": "USD",
    "PaymentMethod": "Debit Card",
    "TransactionCategory": "Shopping",
    "TransactionTags": ["Clothing", "Shopping"],
    "UserID": "1234",
    "MerchantID": "9876",
    "Location": "789 Main St"
  },
  {
    "TransactionID": "15",
    "DateTime": "2023-10-13T12:30:00",
    "Amount": 20.00,
    "Description": "Lunch at work",
    "AccountFrom": "Savings Account",
    "AccountTo": "Cafeteria",
    "TransactionType": "Dining",
    "Status": "Completed",
    "ReferenceNumber": "LUNCH456",
    "Currency": "USD",
    "PaymentMethod": "Employee Card",
    "TransactionCategory": "Dining",
    "TransactionTags": ["Work", "Food"],
    "UserID": "5678",
    "MerchantID": "3456",
    "Location": "101 Oak St"
  },
  {
    "TransactionID": "16",
    "DateTime": "2023-10-12T14:00:00",
    "Amount": 70.00,
    "Description": "Gym membership",
    "AccountFrom": "Checking Account",
    "AccountTo": "Gym",
    "TransactionType": "Subscription",
    "Status": "Completed",
    "ReferenceNumber": "GYM001",
    "Currency": "USD",
    "PaymentMethod": "Credit Card",
    "TransactionCategory": "Health",
    "TransactionTags": ["Gym", "Health"],
    "UserID": "2345",
    "MerchantID": "5678",
    "Location": "456 Elm St"
  },
  {
    "TransactionID": "17",
    "DateTime": "2023-10-11T10:15:00",
    "Amount": 10.00,
    "Description": "Parking fee",
    "AccountFrom": "Savings Account",
    "AccountTo": "Parking Lot",
    "TransactionType": "Fee",
    "Status": "Completed",
    "ReferenceNumber": "PARK001",
    "Currency": "USD",
    "PaymentMethod": "Cash",
    "TransactionCategory": "Transportation",
    "TransactionTags": ["Parking", "Transportation"],
    "UserID": "7890",
    "MerchantID": "1234",
    "Location": "101 Elm St"
  },
  {
    "TransactionID": "18",
    "DateTime": "2023-10-10T13:30:00",
    "Amount": 60.00,
    "Description": "Home improvement",
    "AccountFrom": "Checking Account",
    "AccountTo": "Home Improvement Store",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "HOME001",
    "Currency": "USD",
    "PaymentMethod": "Debit Card",
    "TransactionCategory": "Home",
    "TransactionTags": ["Home", "Shopping"],
    "UserID": "3456",
    "MerchantID": "9876",
    "Location": "789 Oak St"
  },
  {
    "TransactionID": "19",
    "DateTime": "2023-10-09T17:00:00",
    "Amount": 30.00,
    "Description": "Coffee with colleagues",
    "AccountFrom": "Savings Account",
    "AccountTo": "Cafe",
    "TransactionType": "Dining",
    "Status": "Completed",
    "ReferenceNumber": "COFFEE002",
    "Currency": "USD",
    "PaymentMethod": "Credit Card",
    "TransactionCategory": "Dining",
    "TransactionTags": ["Cafe", "Food"],
    "UserID": "2345",
    "MerchantID": "5678",
    "Location": "456 Main St"
  },
  {
    "TransactionID": "20",
    "DateTime": "2023-10-08T16:45:00",
    "Amount": 80.00,
    "Description": "Electronics purchase",
    "AccountFrom": "Savings Account",
    "AccountTo": "Electronics Store",
    "TransactionType": "Purchase",
    "Status": "Completed",
    "ReferenceNumber": "ELEC003",
    "Currency": "USD",
    "PaymentMethod": "Debit Card",
    "TransactionCategory": "Shopping",
    "TransactionTags": ["Electronics", "Shopping"],
    "UserID": "7890",
  "MerchantId":"2612",
  "Location" :"342 Main Str"

  }
]
